# Generated by Django 2.2.6 on 2019-10-19 11:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('position',), 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterField(
            model_name='page',
            name='app_instance_namespace',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='app instance namespace'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.Page', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(db_index=True, editable=False, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Position is expected to be greater than zero.')]),
        ),
    ]
